AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Instance Using CloudFormation"

Parameters:
  amiId:
    Description: "EC2 AMI ID"
    Type: String
    Default: "ami-0e1d35993cb249cee"

  instanceType:
    Description: "Ec2 Instance Type"
    Type: String
    Default: "t3.micro"
    AllowedValues:
      - "t3.micro"
      - "t3.small"

  securityGroupID:
    Description: "Security Group ID"
    Type: String
    Default: "sg-0a18a00bc04437d2b"

  keyPairName:
    Description: "Ec2 KeyPair Name"
    Type: String
    Default: "aws-trn-2025-oregon"

Resources:
  #checklist to create ec2 instance
  #ami
  #instance type
  #security groups
  #keypairs

  ec2Instance:
    Type: AWS::EC2::Instance

    Properties:
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 8

      ImageId: !Ref amiId

      InstanceType: !Ref instanceType

      KeyName: !Ref keyPairName

      SecurityGroupIds:
        - !GetAtt ec2SecurityGroup.GroupId

  ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux Server Security Group" # Required
      GroupName: "cfnLinuxSecGroup"
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all Outbound"
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow HTTP"
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80

        - CidrIp: "0.0.0.0/0"
          Description: "Allow SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      VpcId: "vpc-01d46ac9e3d078b01"
