AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Instance Using CloudFormation"

Parameters:
  serverType:
    Description: "EC2 Server Type"
    Type: String
    Default: "LinuxServer"
    AllowedValues:
      - "LinuxServer"
      - "LinuxWebServer"
  instanceType:
    Description: "Ec2 Instance Type"
    Type: String
    Default: "t3.micro"
    AllowedValues:
      - "t3.micro"
      - "t3.small"

  vpcId:
    Description: "VPC ID"
    Type: String
    Default: "vpc-0955e0d762440f964"

  keyPairName:
    Description: "EC2 KeyPair Name"
    Type: String
    Default: "aws-trn-2025"

#Condition
Conditions:
  isLinuxWebServer: !Equals
    - !Ref serverType
    - "LinuxWebServer"

#key value - then another key value pair
Mappings:
  #logicalname
  ec2AMI:
    #toplevelkey
    LinuxServer:
      #secondlevelkey
      amiId: "ami-0341d95f75f311023"
    LinuxWebServer:
      amiId: "ami-038c679c1660c3723"

Resources:
  #checklist to create ec2 instance
  #ami
  #instance type
  #security groups
  #keypairs

  ec2Instance:
    Type: AWS::EC2::Instance

    Properties:
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 8

      ImageId:
        Fn::FindInMap:
          - ec2AMI
          - !Ref serverType
          - amiId

      InstanceType: !Ref instanceType

      KeyName: !Ref keyPairName

      SecurityGroupIds:
        - !GetAtt ec2SecurityGroup.GroupId
        - !If [
            isLinuxWebServer,
            !GetAtt ec2WebSecurityGroup.GroupId,
            AWS::NoValue,
          ]

  ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux Server Security Group" # Required
      GroupName: "cfnLinuxSecGroup"
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all Outbound"
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      VpcId: !Ref vpcId

  ec2WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux WEB Server Security Group" # Required
      GroupName: "cfnLinuxWebSecGroup"
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all Outbound"
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow HTTP"
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
      VpcId: !Ref vpcId
