AWSTemplateFormatVersion: 2010-09-09
Description: "Sample Lambda Function Using CloudFormation"


Parameters:
  functionName:
    Description: "Lambda Function Name"
    Type: String
    Default: fnHelloWorldCfn

  s3Bucket:
    Description: "S3 Bucket of the lambda Function"
    Type: String
    Default: "mdr-trn-cfn-scripts"

  lambdaZipFile:
    Description: "Lambda Zip File in the bucket's lambda/folder"
    Type: String
    Default: "s3_lambda-v0.zip"

  lambdaHandler:
    Description: "Lambda handler function name"
    Type: String
    Default: "s3_lambda.handler"

  s3Bucketomonitor:
    Type: String
    Description: "s3 bucket name that we will monitor"
    Default: "mdr-trn-s3lambda-int"

#Resources
Resources: 


  lambdaFunction:
    Type: AWS::Lambda::Function

    Properties:

      Code:
        S3Bucket: !Ref s3Bucket
        S3Key: !Join ["/",["lambda",!Ref lambdaZipFile]]

      Description: "Sample Lambda using CloudFormation"

      FunctionName: !Ref functionName
      Handler: !Ref lambdaHandler


      Role: !GetAtt lambdaFunctionRole.Arn
      Runtime: "python3.12"

      Timeout: 60


  lambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Principal: 
                Service: 
                  - "lambda.amazonaws.com"
              Action: 
                - "sts:AssumeRole"

        Description: !Join [" ",["IAM Role for",!Ref functionName, "lambda function"]]
        RoleName: !Join ["-",[!Ref functionName,"lambda","role"]]
        Policies:
          - PolicyName: !Join ["-",[!Ref functionName,"execution","policy"]]
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                  Resource:
                    - "arn:aws:logs:*:*:*"

                - Effect: Allow
                  Action:
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    - !Join ["",["arn:aws:logs:*:*:log-group:/aws/lambda/",!Ref functionName ,":*"]]

  myS3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: s3LambdaInvokePermission
    Properties:
      BucketName: !Ref s3Bucketomonitor
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt lambdaFunction.Arn


  s3LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction" 
      FunctionName: !GetAtt lambdaFunction.Arn
      #Trigger
      Principal: "s3.amazonaws.com"
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Join ["",["arn:aws:s3:::",!Ref s3Bucketomonitor]]

