  registerApiLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction" 
      FunctionName: !GetAtt registerLambdaFunction.Arn
      #Trigger
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Join ["",["arn:aws:execute-api:",!Ref "AWS::Region",":",!Ref "AWS::AccountId",":",!Ref restApi,"/*"]]